pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker compose -f lesson_31/docker-compose.yaml build'
            }
        }
        stage('Run Tests in Docker') {
            steps {
                script {
                    try {
                        sh 'docker compose -f lesson_31/docker-compose.yaml up --abort-on-container-exit --exit-code-from tests'
                    } finally {
                        sh 'docker compose -f lesson_31/docker-compose.yaml down'
                    }
                }
            }
        }
        stage('Copy Test Results') {
            steps {
                sh 'docker cp $(docker compose -f lesson_31/docker-compose.yaml ps -q tests):/app/results.xml ./results.xml || true'
            }
        }
        stage('Publish Test Results') {
            steps {
                catchError(buildResult: 'SUCCESS', stageResult: 'FAILURE') {
                    junit 'results.xml'
                }
            }
        }
    }
    post {
        always {
            emailext (
                to: 'saydanya@gmail.com',
                subject: "Jenkins Pipeline: Build ${currentBuild.fullDisplayName}",
                body: "Build result: ${currentBuild.currentResult}"
            )
        }
    }
}
